Flask/app/views/matrix_calc.py
from flask import (
    render_template,
    Blueprint,
    request,
    send_file,
)
from app.models import Matrix
import os

matrix_calc_blueprint = Blueprint(
    "matrix_calc", __name__, url_prefix="/calculator/matrix"
)


@matrix_calc_blueprint.route("/", methods=["GET"])
def calculator():
    return render_template("calc/matrixCalc.html", rows=3, cols=3)


@matrix_calc_blueprint.route("/", methods=["POST"])
def calculator_post():
    args = request.form.to_dict()

    matrix_dict_a = {k: v for k, v in args.items() if k.startswith("a")}
    rows_a = max([int(key.split("_")[1]) for key in matrix_dict_a.keys()]) + 1
    cols_a = max([int(key.split("_")[2]) for key in matrix_dict_a.keys()]) + 1
    matrix_a = Matrix.fromdict(matrix_dict_a, rows_a, cols_a)

    matrix_dict_b = {k: v for k, v in args.items() if k.startswith("b")}
    rows_b = max([int(key.split("_")[1]) for key in matrix_dict_b.keys()]) + 1
    cols_b = max([int(key.split("_")[2]) for key in matrix_dict_b.keys()]) + 1
    matrix_b = Matrix.fromdict(matrix_dict_b, rows_b, cols_b)
    result = None

    try:
        if request.form.get("save_button_a"):
            download_dir = os.path.join(os.path.expanduser("~"), "Downloads")
            with open(os.path.join(download_dir, "matrixA.txt"), "w") as f:
                for i in range(rows_a):
                    for j in range(cols_a):
                        f.write(str(matrix_a.data[i][j]) + " ")
                    f.write("\n")
            return send_file(
                os.path.join(download_dir, "matrixA.txt"), as_attachment=True
            )

        elif request.form.get("save_button_b"):
            download_dir = os.path.join(os.path.expanduser("~"), "Downloads")
            with open(os.path.join(download_dir, "matrixB.txt"), "w") as f:
                for i in range(rows_b):
                    for j in range(cols_b):
                        f.write(str(matrix_b.data[i][j]) + " ")
                    f.write("\n")
            return send_file(
                os.path.join(download_dir, "matrixB.txt"), as_attachment=True
            )

        elif request.form.get("calc_button_a"):
            result = [
                matrix_a.max_norm(),
                matrix_a.euclidean_norm(),
                matrix_a.transpose(),
            ]
            return render_template(
                "calc/matrixCalc.html",
                rowsA=rows_a,
                colsA=cols_a,
                rowsB=rows_b,
                colsB=cols_b,
                matrixA=matrix_a.data,
                matrixB=matrix_b.data,
                norm_1=result[0],
                norm_2=result[1],
                result=result[2],
            )
        elif request.form.get("calc_button_b"):
            result = [
                matrix_b.max_norm(),
                matrix_b.euclidean_norm(),
                matrix_b.transpose(),
            ]
            return render_template(
                "calc/matrixCalc.html",
                rowsA=rows_a,
                colsA=cols_a,
                rowsB=rows_b,
                colsB=cols_b,
                matrixA=matrix_a.data,
                matrixB=matrix_b.data,
                norm_1=result[0],
                norm_2=result[1],
                result=result[2],
            )

        elif request.form.get("mul_button"):
            result = (matrix_a * matrix_b).data

        elif request.form.get("sum_button"):
            result = (matrix_a + matrix_b).data

        elif request.form.get("sub_button"):
            result = (matrix_a - matrix_b).data
    except ValueError as ve:
        return render_template(
            "calc/matrixCalc.html",
            rowsA=rows_a,
            colsA=cols_a,
            rowsB=rows_b,
            colsB=cols_b,
            matrixA=matrix_a.data,
            matrixB=matrix_b.data,
            exception=ve,
        )
    except Exception as e:
        return render_template(
            "calc/matrixCalc.html",
            rowsA=rows_a,
            colsA=cols_a,
            rowsB=rows_b,
            colsB=cols_b,
            matrixA=matrix_a.data,
            matrixB=matrix_b.data,
            exception=e,
        )
    return render_template(
        "calc/matrixCalc.html",
        rowsA=rows_a,
        colsA=cols_a,
        rowsB=rows_b,
        colsB=cols_b,
        matrixA=matrix_a.data,
        matrixB=matrix_b.data,
        result=result,
    )

Flask/app/views/systems_calc.py
from flask import render_template, Blueprint, request, send_file
from app.utils import create_matrix_from_dict, create_vector_from_dict
import subprocess
import json
import os

systems_calc_blueprint = Blueprint(
    "systems_calc", __name__, url_prefix="/calculator/systems"
)


@systems_calc_blueprint.route("/", methods=["GET"])
def calculator():
    return render_template("calc/systemsCalc.html", rows=3, cols=3)


@systems_calc_blueprint.route("/", methods=["POST"])
def calculator_post():
    args = request.form.to_dict()
    print(args)
    matrix_dict = {k: v for k, v in args.items() if k.startswith("a")}
    vector_dict = {k: v for k, v in args.items() if k.startswith("b")}
    rows = max([int(key.split("_")[1]) for key in matrix_dict.keys()]) + 1
    cols = max([int(key.split("_")[2]) for key in matrix_dict.keys()]) + 1
    matrix = create_matrix_from_dict(matrix_dict, rows, cols)
    vector = create_vector_from_dict(vector_dict)

    if request.form.get("calc_button"):
        matrix_str = json.dumps(matrix)
        vector_str = json.dumps(vector)
        cmd = [
            "/Users/likor7/University/3.2/Algebra/Linear-Algebra-app/Calculation/Calc/bin/Debug/net6.0/Calc",
            matrix_str,
            vector_str,
        ]
        result = subprocess.run(cmd, capture_output=True, text=True)
        result_data = json.loads(result.stdout)
        return render_template(
            "calc/systemsCalc.html",
            rows=rows,
            cols=cols,
            data=matrix,
            data_b=vector,
            result=result_data,
        )

    elif request.form.get("save_button"):
        download_dir = os.path.join(os.path.expanduser("~"), "Downloads")
        with open(os.path.join(download_dir, "matrix.txt"), "w") as f:
            for i in range(rows):
                for j in range(cols):
                    f.write(str(matrix[i][j]) + " ")
                f.write(str(vector[i]) + "\n")
        return send_file(os.path.join(download_dir, "matrix.txt"), as_attachment=True)
    return "Failed", 400

Flask/app/views/upload.py
from flask import render_template, Blueprint, request
import json
import os

upload_blueprint = Blueprint("upload", __name__, url_prefix="/calculator")


@upload_blueprint.route("/upload/", methods=["GET"])
def upload():
    return render_template("calc/upload.html")


# @upload_blueprint.route("/uploaded/", methods=["POST"])
# def upload_post():
#     fileA = request.files.get('fileA')
#     fileB = request.files.get('fileB')
#     matrix = []
#     vector = []
#     for line in file:
#         row = [float(x) for x in line.decode().split()]
#         matrix.append(row[:-1])
#         vector.append(row[-1])
#     return render_template(
#         "calc/systemsCalc.html",
#         rows=len(matrix),
#         cols=len(matrix[0]),
#         data=matrix,
#         data_b=vector,
#         uploaded=True,
#     )


@upload_blueprint.route("/matrix/uploaded/", methods=["POST"])
def upload_post():
    fileA = request.files.get("fileA")
    fileB = request.files.get("fileB")
    matrix_a = []
    matrix_b = []
    for line in fileA:
        row = [float(x) for x in line.decode().split()]
        matrix_a.append(row[:])
    for line in fileB:
        row = [float(x) for x in line.decode().split()]
        matrix_b.append(row[:])
    return render_template(
        "calc/matrixCalc.html",
        rowsA=len(matrix_a),
        colsA=len(matrix_a[0]),
        rowsB=len(matrix_b),
        colsB=len(matrix_b[0]),
        matrixA=matrix_a,
        matrixB=matrix_b,
        uploaded=True,
    )

Flask/app/templates/calc/calc.html
{% extends "base.html" %} {% block content %}
<div class="container">
   <form class="form" id="form-inputs" role="form" action="{{ url_for('calc.calculator_post') }}" method="POST"
      autocomplete="off">

      <div class="d-flex justify-content-around align-items-center flex-wrap">
         <div class="matrix-table" id="matrix-table">
            <math>
               <mrow>
                  <mo>[</mo>
                  <mtable id="matrix-inputs">
                  </mtable>
                  <mo>]</mo>
               </mrow>
            </math>
         </div>

         <div class="xvector-table">
            <math>
               <mrow>
                  <mo>[</mo>
                  <mtable id="xvector">
                  </mtable>

                  <mo>]</mo>

               </mrow>
            </math>
         </div>
         =
         <div class="vector-table">
            <math>
               <mrow>
                  <mo>[</mo>
                  <mtable id="vector-inputs">
                  </mtable>
                  <mo>]</mo>
               </mrow>
            </math>
         </div>
      </div>
      <div class="row-column-buttons d-flex justify-content-center flex-wrap">
         <button type="button" class="btn btn-outline-success m-2" onclick="addRow()">+ Row</button>
         <button type="button" class="btn btn-outline-danger  m-2" onclick="removeRow()">- Row</button>

         <button type="button" class="btn btn-outline-success m-2" onclick="addColumn()">+ Column</button>
         <button type="button" class="btn btn-outline-danger m-2" onclick="removeColumn()">- Column</button>
      </div>
      <div class="control-buttons row-column-buttons d-flex justify-content-center flex-wrap">
         <button class="btn btn-primary m-2" name="calc_button" value="Calculate" type="submit">Calculate</button>
         <button class="btn btn-primary m-2" name="save_button" value="Save" type="submit">Save Matrix</button>
         <button class="btn btn-primary m-2" onclick="generateRandom(event)">Randomize</button>
      </div>
   </form>
</div>

{% if result %}
{{ result }}
{% endif %}

<script src="{{ url_for('static', filename='js/creationTable.js') }}" type="text/javascript"></script>
<script src="{{ url_for('static', filename='js/random.js') }}" type="text/javascript"></script>
{% if result or uploaded %}
<script>
   const rows = {{ rows| tojson }};
   const cols = {{ cols| tojson }};
   const data = {{ data| tojson }};
   const data_b = {{ data_b| tojson }};
   init_matrix(rows, cols, data, data_b);
</script>
{% elif not(result) %}
<script>
   const rows = {{ rows| tojson }};
   const cols = {{ cols| tojson }};
   init(rows, cols);
</script>
{% endif %}
<script src="{{ url_for('static', filename='js/rowcolumnControl.js') }}" type="text/javascript"></script>
{% endblock %}

Flask/app/templates/calc/matrixCalc.html
{% extends "base.html" %} {% block content %}
<div class="container mt-3">
    <form class="form" id="form-inputs" role="form" action="{{ url_for('matrix_calc.calculator_post') }}" method="POST"
        autocomplete="off">

        <div class="tables-matrix d-flex justify-content-between">
            <div class="matrix-table d-flex flex-column">
                <div class="matrix">
                    <math>
                        <mrow>
                            <mo>[</mo>
                            <mtable id="matrix-inputs-A">
                            </mtable>
                            <mo>]</mo>
                        </mrow>
                    </math>
                </div>
                <div class="row-column-buttons d-flex">
                    <button type="button" class="btn btn-outline-success m-1"
                        onclick="addRowMatrix('matrix-inputs-A', 'a')">+
                        Row</button>
                    <button type="button" class="btn btn-outline-danger m-1"
                        onclick="removeRowMatrix('matrix-inputs-A', 'a')">-
                        Row</button>

                    <button type="button" class="btn btn-outline-success m-1"
                        onclick="addColumnMatrix('matrix-inputs-A', 'a')">+
                        Col</button>
                    <button type="button" class="btn btn-outline-danger m-1"
                        onclick="removeColumnMatrix('matrix-inputs-A', 'a')">-
                        Col</button>
                </div>
            </div>
            <div class="matrix-table d-flex flex-column ml-2">
                <div class="matrix d-flex justify-content-end">
                    <math>
                        <mrow>
                            <mo>[</mo>
                            <mtable id="matrix-inputs-B">
                            </mtable>
                            <mo>]</mo>
                        </mrow>
                    </math>
                </div>
                <div class="row-column-buttons d-flex justify-content-end">
                    <button type="button" class="btn btn-outline-success m-1"
                        onclick="addRowMatrix('matrix-inputs-B', 'b')">+
                        Row</button>
                    <button type="button" class="btn btn-outline-danger m-1"
                        onclick="removeRowMatrix('matrix-inputs-B', 'b')">-
                        Row</button>

                    <button type="button" class="btn btn-outline-success m-1"
                        onclick="addColumnMatrix('matrix-inputs-B', 'b')">+
                        Col</button>
                    <button type="button" class="btn btn-outline-danger m-1"
                        onclick="removeColumnMatrix('matrix-inputs-B', 'b')">-
                        Col</button>
                </div>
            </div>
        </div>
        <hr>

        <div class="control-buttons d-flex justify-content-between ">
            <div class="calc-A d-flex flex-column">
                <p class="text-secondary text-center">A matrix</p>
                <button class="btn btn-outline-dark" name="calc_button_a" value="Calculate"
                    type="submit">Calculate</button>
                <button class="btn btn-outline-dark"
                    onclick="generateRandom(event, 'matrix-inputs-A')">Randomize</button>
                <button class="btn btn-outline-dark" name="save_button_a" value="Save" type="submit">Save
                    Matrix</button>
            </div>

            <div class="calc-A-B d-flex flex-column">
                <button class="btn btn-outline-dark m-2" name="mul_button" value="mul_button" type="submit">A *
                    B</button>
                <button class="btn btn-outline-dark m-2" name="sum_button" value="sum_button" type="submit">A +
                    B</button>
                <button class="btn btn-outline-dark m-2" name="sub_button" value="sub_button" type="submit">A -
                    B</button>
            </div>

            <div class="calc-B d-flex flex-column">
                <p class="text-secondary text-center">B matrix</p>
                <button class="btn btn-outline-dark" name="calc_button_b" value="Calculate"
                    type="submit">Calculate</button>
                <button class="btn btn-outline-dark"
                    onclick="generateRandom(event, 'matrix-inputs-B')">Randomize</button>

                <button class="btn btn-outline-dark" name="save_button_b" value="Save" type="submit">Save
                    Matrix</button>
            </div>

        </div>

        <hr>
    </form>

    <div class="result-area d-flex justify-content-center align-items-center flex-column">
        <p class="text-secondary mr-3">Result:</p>
        {% if result and norm_1 and norm_2 and not(exception)%}
        <p>Max norm: {{ norm_1 |round(2)}}</p>
        <p>Euclidean norm: {{ norm_2 |round(2)}}</p>
        <span>Transposed:</span>
        {% endif %}
        {% if result and not(exception)%}
        <math>
            <mrow>
                <mo>[</mo>
                <mtable>
                    {% for r in result %}
                    <mtr>
                        {% for i in r%}
                        <mtd>
                            <mn>{{ i|round(2) }}</mn>
                        </mtd>
                        {% endfor %}
                    </mtr>
                    {% endfor %}
                </mtable>
                <mo>]</mo>
            </mrow>
        </math>
        <div class="mb-2"></div>
        {% elif exception %}
        <p>{{ exception }}</p>
        {% endif %}
    </div>
</div>

<script src="{{ url_for('static', filename='js/creationMatrix.js') }}" type="text/javascript"></script>
<script src="{{ url_for('static', filename='js/random.js') }}" type="text/javascript"></script>
{% if not(result) and not(exception) and not(uploaded)%}
<script>
    const rows = {{ rows| tojson }};
    const cols = {{ cols| tojson }};
    init(rows, cols);
</script>
{% elif result or exception or uploaded%}
<script>
    const rowsA = {{ rowsA| tojson}};
    const colsA = {{ colsA| tojson}};
    const rowsB = {{ rowsB| tojson}};
    const colsB = {{ colsB| tojson}};
    const matrixA = {{ matrixA| tojson}};
    const matrixB = {{ matrixB| tojson}};
    init_matrix_A(rowsA, colsA, matrixA);
    init_matrix_B(rowsB, colsB, matrixB);
</script>
{% endif %}
<script src="{{ url_for('static', filename='js/control.js') }}" type="text/javascript"></script>
{% endblock %}

Flask/app/templates/calc/systemsCalc.html
{% extends "base.html" %} {% block content %}
<div class="container mt-3">
   <form class="form" id="form-inputs" role="form" action="{{ url_for('systems_calc.calculator_post') }}" method="POST"
      autocomplete="off">

      <div class="d-flex justify-content-around align-items-center flex-wrap">
         <div class="matrix-table">
            <math>
               <mrow>
                  <mo>[</mo>
                  <mtable id="matrix-inputs">
                  </mtable>
                  <mo>]</mo>
               </mrow>
            </math>
         </div>

         <div class="xvector-table">
            <math>
               <mrow>
                  <mo>[</mo>
                  <mtable id="xvector">
                  </mtable>

                  <mo>]</mo>

               </mrow>
            </math>
         </div>
         =
         <div class="vector-table">
            <math>
               <mrow>
                  <mo>[</mo>
                  <mtable id="vector-inputs">
                  </mtable>
                  <mo>]</mo>
               </mrow>
            </math>
         </div>
      </div>
      <div class="row-column-buttons d-flex justify-content-center flex-wrap">
         <button type="button" class="btn btn-outline-success m-2" onclick="addSystem()">+</button>
         <button type="button" class="btn btn-outline-danger m-2" onclick="removeSystem()">-</button>
      </div>
      <div class="control-buttons row-column-buttons d-flex justify-content-center flex-wrap">
         <button class="btn btn-primary m-2" name="calc_button" value="Calculate" type="submit">Calculate</button>
         <button class="btn btn-primary m-2" name="save_button" value="Save" type="submit">Save Matrix</button>
         <button class="btn btn-primary m-2" onclick="generateRandom(event, 'form-inputs')">Randomize</button>
      </div>
   </form>
</div>

{% if result %}
{{ result }}
{% endif %}

<script src="{{ url_for('static', filename='js/creationSystems.js') }}" type="text/javascript"></script>
<script src="{{ url_for('static', filename='js/random.js') }}" type="text/javascript"></script>
{% if result or uploaded %}
<script>
   const rows = {{ rows| tojson }};
   const cols = {{ cols| tojson }};
   const data = {{ data| tojson }};
   const data_b = {{ data_b| tojson }};
   init_matrix(rows, cols, data, data_b);
</script>
{% elif not(result) %}
<script>
   const rows = {{ rows| tojson }};
   const cols = {{ cols| tojson }};
   init(rows, cols);
</script>
{% endif %}
<script src="{{ url_for('static', filename='js/control.js') }}" type="text/javascript"></script>
<script>
   const addSystem = () => {
      addRowMatrix("matrix-inputs");
      addRowVectors();
      addColumnMatrix("matrix-inputs");
   }

   const removeSystem = () => {
      removeRowMatrix("matrix-inputs", 'a');
      removeRowVectors();
      removeColumnMatrix("matrix-inputs", 'a');
   }
</script>
{% endblock %}

Flask/app/templates/calc/upload.html
{% extends "base.html" %} {% block content %}
<div class="container py-4 ">
    <div class="card w-50 mx-auto">
        <div class="card-header">
            <div class="input-group">
                <label class="input-group-text" for="template-selector">Select</label>
                <select class="form-select" id="template-selector">
                    <option selected value="matrix">Matrix</option>
                    <option value="systems">Systems</option>
                </select>
            </div>
        </div>
        <div class="card-body" id="template-container">

        </div>
    </div>
</div>

<script src="{{ url_for('static', filename='js/uploadSelect.js') }}" type="text/javascript"></script>
{% endblock %}